"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2
# enable_cursor_positioning = true

[palette]
os = "#ACB0BE"
closer = "p:os"
pink = "#F5BDE6"
lavender = "#B7BDF8"
blue = "#8AADF4"

[[blocks]]
alignment = "left"
type = "prompt"
newline = true
#filler = "|"

  [[blocks.segments]]
  type = "path"
  style = "powerline"
   powerline_symbol = ""
  foreground = "p:pink"
  template = "{{ .Path }} "

    [blocks.segments.properties]
    folder_icon = ".."
    home_icon = "~"
    style = "agnoster"

  [[blocks.segments]]
  foreground = "p:lavender"
  template = "{{ .HEAD }} "
  style = "plain"
  type = "git"

    [blocks.segments.properties]
    branch_icon = " "
    cherry_pick_icon = " "
    commit_icon = " "
    fetch_status = true
    fetch_upstream_icon = true
    merge_icon = " "
    no_commits_icon = " "
    rebase_icon = " "
    revert_icon = " "
    tag_icon = " "

  [[blocks.segments]]
  style = "plain"
  foreground = "p:closer"
  template = ""
  type = "text"

