"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[palette]


[[blocks]]
type = "prompt"
alignment = "left"

   [[blocks.segments]]
   type = "path"
   style = "powerline"
   template = "{{ .Path }}"
   foreground = "#CAD3F5"
   #background = "#24273A"
   background = "transparent"
      
      [blocks.segments.properties]
      style = "full"
