# This is the configuration file for catnip.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnip

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username = {icon = " ", name = "user", color = "(RD)"}
hostname = {icon = " ", name = "hname", color = "(YW)"}
uptime   = {icon = " ", name = "uptime", color = "(BE)"}
distro   = {icon = " ", name = "distro", color = "(GN)"}
kernel   = {icon = " ", name = "kernel", color = "(MA)"}
desktop  = {icon = " ", name = "desktp", color = "(CN)"}
terminal = {icon = " ", name = "term", color = "(RD)"}
shell    = {icon = " ", name = "shell", color = "(MA)"}
memory   = {icon = " ", name = "memory", color = "(YW)"}
disk_0   = {icon = " ", name = "root(/)", color = "(GN)"}
disk_2   = {icon = " ", name = "home(~)", color = "(GN)"}
colors   = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##               Misc Config                ##
##############################################
[misc]
borderstyle = "dotted" #[line (The default border style.), dashed, dotted, noborder, doubleline]
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]

[misc.figletLogos]
enable = false
color  = "(YW)"
font   = "slant"
margin = [0, 0, 0,]

[misc.imageMode]
enable = true
path = "/home/gryd/.config/catnap/kanagawa_wave_500.png"
scale = 27
margin = [-1, 2, 1,]
